package main

import (
	"fmt"

	_ "github.com/whatap/golib/config"
	_ "github.com/whatap/golib/config/conffile"
	_ "github.com/whatap/golib/io"
	_ "github.com/whatap/golib/lang/pack"
	_ "github.com/whatap/golib/lang/pack/open"
	_ "github.com/whatap/golib/lang/pack/udp"
	_ "github.com/whatap/golib/lang/ref"
	_ "github.com/whatap/golib/lang/service"
	_ "github.com/whatap/golib/lang/step"
	_ "github.com/whatap/golib/lang/value"
	_ "github.com/whatap/golib/lang/variable"
	_ "github.com/whatap/golib/logger"
	_ "github.com/whatap/golib/logger/logfile"
	_ "github.com/whatap/golib/logsink/zip"

	_ "github.com/whatap/golib/net"
	_ "github.com/whatap/golib/net/oneway"
	_ "github.com/whatap/golib/net/udp"
	_ "github.com/whatap/golib/openmx"
	_ "github.com/whatap/golib/util/ansi"
	_ "github.com/whatap/golib/util/bitutil"
	_ "github.com/whatap/golib/util/cmdutil"
	_ "github.com/whatap/golib/util/compare"
	_ "github.com/whatap/golib/util/dateutil"
	_ "github.com/whatap/golib/util/hash"
	_ "github.com/whatap/golib/util/hexa32"
	_ "github.com/whatap/golib/util/hll"
	_ "github.com/whatap/golib/util/hmap"
	_ "github.com/whatap/golib/util/iputil"
	_ "github.com/whatap/golib/util/keygen"
	_ "github.com/whatap/golib/util/list"
	_ "github.com/whatap/golib/util/mathutil"
	_ "github.com/whatap/golib/util/openstack"
	_ "github.com/whatap/golib/util/paramtext"
	_ "github.com/whatap/golib/util/queue"
	_ "github.com/whatap/golib/util/stringutil"
	_ "github.com/whatap/golib/util/urlutil"
	_ "github.com/whatap/golib/util/uuidutil"
	// _ "github.com/whatap/golib/agent/agent/active"
	// _ "github.com/whatap/golib/agent/agent/alert"
	// _ "github.com/whatap/golib/agent/agent/boot"
	// _ "github.com/whatap/golib/agent/agent/config"
	// _ "github.com/whatap/golib/agent/agent/control"
	// _ "github.com/whatap/golib/agent/agent/counter"
	// _ "github.com/whatap/golib/agent/agent/counter/meter"
	// _ "github.com/whatap/golib/agent/agent/countertag"
	// _ "github.com/whatap/golib/agent/agent/data"
	// _ "github.com/whatap/golib/agent/agent/kube"
	// _ "github.com/whatap/golib/agent/agent/pprof"
	// _ "github.com/whatap/golib/agent/agent/secure"
	// _ "github.com/whatap/golib/agent/agent/stat"
	// _ "github.com/whatap/golib/agent/agent/topology"
	// _ "github.com/whatap/golib/agent/agent/trace"
	// _ "github.com/whatap/golib/agent/agent/trace/api"
	// _ "github.com/whatap/golib/agent/alert"
	// _ "github.com/whatap/golib/agent/lang/conf"
	// _ "github.com/whatap/golib/agent/logsink/watch"
	// _ "github.com/whatap/golib/agent/logsink/zip"
	// _ "github.com/whatap/golib/agent/util/crypto"
	// _ "github.com/whatap/golib/agent/util/logutil"
	// _ "github.com/whatap/golib/agent/util/oidutil"
	// _ "github.com/whatap/golib/agent/util/sqlutil"
	// _ "github.com/whatap/golib/agent/util/sys"
)

func main() {
	fmt.Println("Whatap Golang common library")
}
